import { StyleSheet } from 'react-native';

export const C = {
  green: '#293D34', paper: '#F7F7F2', card: '#FDFDF9', muted: '#667168',
  line: '#E2E6DD', soft: '#EAF0E5', amber: '#F0EDE2',
};

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.paper },
  content: { flexGrow: 1, width: '100%', maxWidth: 560, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 16, paddingBottom: 32 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, paddingVertical: 8 },
  brandText: { color: C.green, fontSize: 18, fontWeight: '500', letterSpacing: -.4 },
  avatar: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: C.muted, fontSize: 21 },
  onboarding: { flex: 1, justifyContent: 'center', paddingBottom: 64 },
  headline: { fontSize: 28, fontWeight: '400', letterSpacing: -.7, color: C.green, lineHeight: 36, marginBottom: 12 },
  introText: { color: C.muted, fontSize: 15, lineHeight: 23, marginBottom: 28 },
  sectionTitle: { color: C.muted, fontSize: 13, marginTop: 28, marginBottom: 16 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  tabs: { flexDirection: 'row', gap: 28, borderBottomWidth: 1, borderColor: C.line, marginBottom: 24 },
  tab: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 14, minHeight: 48 },
  tabActive: { borderBottomWidth: 1, borderColor: C.green },
  tabText: { fontSize: 15, color: C.muted }, tabTextActive: { color: C.green, fontWeight: '500' },
  countText: { color: C.muted, fontSize: 12 },
  card: { backgroundColor: C.card, borderWidth: 1, borderColor: C.line, borderRadius: 16, padding: 20, marginBottom: 20 },
  serviceText: { fontSize: 13, color: C.muted, flexShrink: 1 },
  badgeText: { fontSize: 12, color: C.muted, flexShrink: 1 },
  cardTitle: { fontSize: 22, letterSpacing: -.4, fontWeight: '500', color: C.green, marginTop: 16, marginBottom: 10, lineHeight: 29 },
  summary: { fontSize: 14, color: C.muted, lineHeight: 22, marginBottom: 20 },
  details: { marginBottom: 16 },
  detail: { flexDirection: 'row', gap: 16, borderTopWidth: 1, borderColor: C.line, paddingVertical: 12 },
  detailLabel: { width: 80, color: C.muted, fontSize: 13, lineHeight: 20 },
  detailValue: { flex: 1, fontSize: 14, lineHeight: 20, color: C.green },
  meta: { color: C.muted, fontSize: 12, lineHeight: 18 },
  slide: { height: 60, marginTop: 16, backgroundColor: C.soft, borderRadius: 30, justifyContent: 'center', paddingLeft: 56 },
  slideText: { textAlign: 'center', color: C.green, fontSize: 14, paddingRight: 16 },
  thumb: { position: 'absolute', left: 6, top: 6, width: 48, height: 48, backgroundColor: C.green, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  thumbText: { fontSize: 26, color: C.paper, marginTop: -2 },
  hint: { color: C.muted, fontSize: 12, lineHeight: 19, marginTop: 10 },
  reject: { alignItems: 'center', justifyContent: 'center', minHeight: 48, marginTop: 8 },
  rejectText: { color: C.muted, fontSize: 14 },
  eventButton: { minHeight: 48, justifyContent: 'center', marginTop: 8 },
  event: { fontSize: 13, color: C.muted, lineHeight: 21, marginTop: 8 },
  primary: { minHeight: 52, backgroundColor: C.green, borderRadius: 14, paddingHorizontal: 20, paddingVertical: 16, alignItems: 'center', justifyContent: 'center' },
  primaryText: { color: C.paper, fontSize: 15, fontWeight: '500' },
  disabled: { opacity: .5 },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 64, paddingBottom: 96 },
  emptyIcon: { height: 48, width: 48, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  emptyCheck: { fontSize: 26, color: C.muted },
  emptyTitle: { fontSize: 17, color: C.muted, textAlign: 'center' },
  demo: { paddingVertical: 10, marginBottom: 12 }, demoText: { fontSize: 12, lineHeight: 18, color: C.muted }, demoButton: { minHeight: 48, justifyContent: 'center', marginBottom: 12 },
  error: { backgroundColor: '#F4E9E4', borderRadius: 12, padding: 14, marginBottom: 16 }, errorText: { color: '#803A30', fontSize: 14, lineHeight: 21 },
  notice: { paddingVertical: 12, marginBottom: 12 }, noticeText: { color: C.green, fontSize: 14, lineHeight: 21 },
  settingButton: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, paddingVertical: 16, borderBottomWidth: 1, borderColor: C.line },
  settingText: { color: C.green, fontSize: 15, lineHeight: 22 },
  connection: { paddingVertical: 16, borderBottomWidth: 1, borderColor: C.line },
  pairingContent: { paddingTop: 28 },
  pairingForm: { paddingTop: 8 },
  input: { minHeight: 52, borderWidth: 1, borderColor: C.line, borderRadius: 12, padding: 14, marginTop: 16, marginBottom: 8, color: C.green, fontSize: 15, backgroundColor: C.card },
  camera: { height: 300, borderRadius: 16, overflow: 'hidden', marginBottom: 16 },
});
